#!/system/bin/sh

export BASE=/data/data/ca.nicholaspaun.chemlogic.app1/files/system
export PATH=${BASE}/bin:/sbin:/system/sbin:/system/bin:/system/xbin:${BASE}/lib
export LD_LIBRARY_PATH=/system/lib:${BASE}/lib:/lib:/usr/lib

${BASE}/lib/ld-linux.so.3 $BASE/bin/chemcli

