#!/system/bin/sh

export BASE=/data/data/ca.nicholaspaun.chemlogic.20/angstrom
export PATH=${BASE}/bin:/sbin:/system/sbin:/system/bin:/system/xbin:${BASE}/lib/
export LD_LIBRARY_PATH=/system/lib:${BASE}/lib:/lib:/usr/lib

echo $0
${BASE}/lib/ld-linux.so.3 ${BASE}/bin/busybox.nosuid chroot ${BASE} /bin/sh /etc/rc

